#!/usr/bin/env python3
#
# Problem: when you copy text from windows to a unix console, you get all
# kinds of odd characters in the text.
#
# This is a rough tool to sanitise such text towards 7-bit ascii.
#

import sys

SWAPS = [ ('\xe2\x80\x98', "'")
        , ('\xe2\x80\x99', "'")

        , ('\xe2\x80\x9c', '"')
        , ('\xe2\x80\x9d', '"')

        # emdash
        , ('\xe2\x80\x94', '-')

        # elipse
        , ('\xe2\x80\xa6', '...')
        ]

def read_file(fname):
    f_ptr = open(fname)
    data = f_ptr.read()
    f_ptr.close()
    print("Read %s"%fname)
    return data

def write_file(fname, data):
    f_ptr = open(fname, 'w+')
    f_ptr.write(data)
    f_ptr.close()
    print("Wrote %s"%fname)

def main():
    for fname in sys.argv[1:]:
        data = read_file(fname)

        # Replace common exceptions with new characters.
        for old, new in SWAPS:
            data = new.join( data.split(old) )

        # Neutralise anything that is not 7-bit ascii
        sb = []
        for c in data:
            if ord(c) < 32:
                c = '|%s|'%(ord(c))
            elif ord(c) >= 127:
                c = '|%s|'%(ord(c))
            sb.append(c)
                
        data = ''.join(data)
        write_file(fname, data)

if __name__ == '__main__':
    main()

