# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

export EDITOR=vim
export PATH=$PATH:$HOME/bin:/sbin:/usr/sbin
export PS1='\h\$ '

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

alias l='ls -lF'
alias ll='ls -laF'
alias cl='clear; ls -lF'
alias cll='clear; ls -laF'
alias now='date +%Y%m%d'
alias grep='grep --color=auto'

set -o vi

